server:
  port: 9003

spring:
  application:
    name: API-GATEWAY

cloud:
  gateway:
    routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/employees/**

      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
          - Path=/products/**

      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
          - Path=/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
  service-url:
    defaultZone: http://localhost:8761/eureka/
